### ISSUE TITLE
Provide citations

### ISSUE THREAD

**Issue by hborders** [mbbx6spp/styleguides#21]
Provide a citation for the local vs. exported naming convention.
Provide citations for the conventions section
Provide citations for the variables section.
Provide citations for the functions section.
Provide citations for the errors section.
Provide citations for the naming section.
Provide citations for the structure section.

**Comment by mbbx6spp** [comment]
Errors section citation for the reference table will be resolved by #20 (a work in progress).

Unless there is specific reference information included (e.g. the exit codes), most of these conventions are just conventions *I* and related parties (team mates) have used to greater effect on Bash scripts. I have tried to keep the style conventions listed in the second part (the first part is more like a tutorial of sorts) consistent with well written consistent Bash script seen elsewhere (e.g. environment variables should be upper case and script level variables should be lower camel case names).

I think what I might do in #20 is separate out the tutorial kind stuff from the style guide itself as that separation is not clear.

Besides the exit codes table, let me know if I am missing adding a reference for the non-convention stuff.

Cheers.

**Comment by mbbx6spp** [comment]
As an FYI I tried to convey the purpose of the repository as a starting point that should be changed per team/organization as seen fit here:
https://github.com/mbbx6spp/styleguides#intent

As that may have been lacking before. Thanks for the issue. It forced me to revisit how I structured and communicated the purpose of the repository.
